name: Firebase Continues Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build
        env:
           CI: ""
           REACT_APP_API_KEY: ${{ secrets.API_KEY }}
           REACT_APP_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
           REACT_APP_DATABASE_URL: ${{ secrets.DATABASE_URL }}
           REACT_APP_PROJECT_ID: ${{ secrets.PROJECT_ID }}
           REACT_APP_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
           REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
           REACT_APP_APP_ID: ${{ secrets.APP_ID }}
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
